import {
  getScope,
  getToken,
  loginAsIntegration,
  loginAsGuest,
  setMarket,
  getMarket,
  loginAsCustomer,
  isCustomerLoggedIn,
  logoutCustomer,
  getCustomerToken,
  useCustomerSession,
  loadProfile,
  getProfile,
  cacheToken,
} from './session'

export const Auth = {
  setMarket,
  getMarket,
  getScope,
  loginAsGuest,
  loginAsCustomer,
  isCustomerLoggedIn,
  logoutCustomer,
  loginAsIntegration,
  getToken,
  getCustomerToken,
  useCustomerSession,
  loadProfile,
  getProfile,
  __setCurrentToken: cacheToken,
}
